sudo: required
dist: xenial

language: haxe

os:
  - linux
  
haxe:
  - "3.4.7"
  - "4.0.5"
  - "4.1.0"
  - "4.0.0-rc.3"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    - haxe: 4.0.0-rc.3
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  - haxelib run travix php
  - haxelib run travix lua
  - haxelib run travix hl